version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: innocart-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_cart
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./migrations/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  redis:
    image: redis:7-alpine
    container_name: innocart-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: innocart-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=smart_cart
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=production-secret-innocart-v2
      - USE_MOCK_PAYMENTS=true
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: innocart-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
